default: &default
  adapter: postgresql
  encoding: unicode
  username: sadat
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
    <<: *default
    database: quiz-backend_development

test:
  <<: *default
  database: quiz-backend_test


production:
  <<: *default
  database: quiz-backend_production
  username: quiz-backend
  password: <%= ENV['QUIZ-BACKEND_DATABASE_PASSWORD'] %>
