default: &default
  adapter: postgresql
  encoding: unicode
  DATABASE_HOST: postgres
  username: sadat
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quiz-backend_development

test:
  <<: *default
  database: quiz-backend_test
  username: sadat


production:
  <<: *default
  DATABASE_PORT: 5432
  DATABASE_HOST: 127.0.0.1
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
