default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quiz-backend_development

test:
  <<: *default
  database: quiz-backend_test
  username: postgres


production:
  <<: *default
    adapter: postgresql
    host: <%= ENV.fetch('DATABASE_HOST') %>
    port: <%= ENV.fetch('DATABASE_PORT') %>
    username: <%= ENV.fetch('DATABASE_USERNAME') %>
    password: <%= ENV.fetch('DATABASE_PASSWORD') %>
